FIx MSVC linker error
The "error c1007: unrecognized flag '-archsse2'" occurred due to the MSVC version difference used to build the static libraries.